# Generated by Django 3.2.3 on 2021-05-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('join_date', models.DateField()),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
