# Generated by Django 3.2.3 on 2021-05-28 11:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_join_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(10)])),
                ('task_des', models.CharField(max_length=2000, null=True)),
                ('task_file', models.FileField(blank=True, upload_to='task')),
                ('create_on_time', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
